In [9]:
a = [1,2,3,4]
print(list(enumerate(a)))

[(0, 1), (1, 2), (2, 3), (3, 4)]


In [10]:
x = 2
def foo(y):
    x = 41
    z = 5
    print(locals())
    print (globals()['x'])
    print(x,y,z)

foo(3)

{'y': 3, 'x': 41, 'z': 5}
2
41 3 5


In [13]:
x = [5]

def foo(x):
    x.append(3)

foo(x)
print(x)

[5, 3]


In [10]:
import numpy as np

arr = np.fromiter((x*x for x in range(5)), dtype='int')
print(arr)

[ 0  1  4  9 16]


In [11]:
arrr = np.array([1.5, False, 'hello'])
arrr

array(['1.5', 'False', 'hello'], dtype='<U32')

In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4],[5,6],[7,8]])
c = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]])
print(a.shape)
print(b.shape)
print(c.shape)

try:
    print(a+b)
except:
    print(a.shape, b.shape)

try:
    print(b+c)
except:
    print(b.shape, c.shape)
    
try:
    print(a+c)
except:
    print(a.shape, c.shape)    

try:
    print(a+b+c)
except:
    print(a.shape, b.shape, c.shape)

(2, 2)
(4, 2)
(4, 4)
(2, 2) (4, 2)
(4, 2) (4, 4)
(2, 2) (4, 4)
(2, 2) (4, 2) (4, 4)


In [18]:
np.arange(4) + np.ones(5)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [19]:
np.arange(4).reshape(4,1) + np.ones(5)

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [25]:
print(np.arange(4).reshape(4,1), np.arange(4).reshape(4,1).shape)

[[0]
 [1]
 [2]
 [3]] (4, 1)


In [26]:
print(np.ones(5), np.ones(5).shape)

[1. 1. 1. 1. 1.] (5,)


In [29]:
np.ones(5).shape == np.ones(5).reshape(1,5).shape

False

In [23]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [20]:
np.arange(4) + np.ones((3,4))

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [28]:
np.array([0, 10, 20, 30])[:, np.newaxis] + np.array([1,2,3])

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [37]:
A = np.array([[1,2],[3,4],[5,6]])
a0, a1 = A.shape

# C style
for i in range(a0):
    for j in range(a1):
        print(f'({i},{j})    {A[i,j]}')

print()
# Fortran Style
for i in range(a1):
    for j in range(a0):
        print(f'({j},{i})    {A[j,i]}')

(0,0)    1
(0,1)    2
(1,0)    3
(1,1)    4
(2,0)    5
(2,1)    6

(0,0)    1
(1,0)    3
(2,0)    5
(0,1)    2
(1,1)    4
(2,1)    6


In [39]:
print(np.ravel(A, order="C"))
print(np.ravel(A, order='F'))

[1 2 3 4 5 6]
[1 3 5 2 4 6]


In [48]:
import pandas as pd

df = pd.DataFrame([24,24,24,17,29,2,74])
df[[0]]

0
0  24
1  24
2  24
3  17
4  29
5   2
6  74

In [49]:
data = pd.read_csv('datasets/dogs.csv')
data

name        breed  color  height_cm  weight_kg date_of_birth
0    Bella     Labrador  Brown         56         25    2013-07-01
1  Charlie       Poodle  Black         43         23    2016-09-16
2     Lucy    Chow Chow  Brown         46         22    2014-08-25
3   Cooper    Schnauzer   Gray         49         17    2011-12-11
4      Max     Labrador  Black         59         29    2017-01-20
5   Stella    Chihuahua    Tan         18          2    2015-04-20
6   Bernie  St. Bernard  White         77         74    2018-02-27

In [83]:
asdf = data.pivot_table('height_cm', index='breed', columns='color')
asdf

color        Black  Brown  Gray   Tan  White
breed                                       
Chihuahua      NaN    NaN   NaN  18.0    NaN
Chow Chow      NaN   46.0   NaN   NaN    NaN
Labrador      59.0   56.0   NaN   NaN    NaN
Poodle        43.0    NaN   NaN   NaN    NaN
Schnauzer      NaN    NaN  49.0   NaN    NaN
St. Bernard    NaN    NaN   NaN   NaN   77.0

In [78]:
data_srt = data.set_index(['breed','color']).sort_index()
data_srt

name  height_cm  weight_kg date_of_birth
breed       color                                             
Chihuahua   Tan     Stella         18          2    2015-04-20
Chow Chow   Brown     Lucy         46         22    2014-08-25
Labrador    Black      Max         59         29    2017-01-20
            Brown    Bella         56         25    2013-07-01
Poodle      Black  Charlie         43         23    2016-09-16
Schnauzer   Gray    Cooper         49         17    2011-12-11
St. Bernard White   Bernie         77         74    2018-02-27

In [82]:
data_srt.loc[('Chihuahua', 'Tan'):('Schnauzer', 'Gray')]

name  height_cm  weight_kg date_of_birth
breed     color                                             
Chihuahua Tan     Stella         18          2    2015-04-20
Chow Chow Brown     Lucy         46         22    2014-08-25
Labrador  Black      Max         59         29    2017-01-20
          Brown    Bella         56         25    2013-07-01
Poodle    Black  Charlie         43         23    2016-09-16
Schnauzer Gray    Cooper         49         17    2011-12-11

In [73]:
print(type([]), type(data.columns))

#for i in data.columns:
#    print(i)

<class 'list'> <class 'pandas.core.indexes.base.Index'>


In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   name           7 non-null      object
 1   breed          7 non-null      object
 2   color          7 non-null      object
 3   height_cm      7 non-null      int64 
 4   weight_kg      7 non-null      int64 
 5   date_of_birth  7 non-null      object
dtypes: int64(2), object(4)
memory usage: 464.0+ bytes


In [63]:
data.groupby('color')['weight_kg'].agg([min, max, sum])

min  max  sum
color               
Black   23   29   52
Brown   22   25   47
Gray    17   17   17
Tan      2    2    2
White   74   74   74

In [86]:
def scaled_sum(*args, scale=1):
    return sum(args) * scale

print(scaled_sum(1,2,3))
print(scaled_sum(1,5))
print(scaled_sum(1,5,scale=10))

6
6
60


In [94]:
def cache(func):
    func._cache = {}
    def wrapper(*args):
        if args not in func._cache:
            func._cache[args] = func(*args)
        return func._cache[args]
    return wrapper


@cache
def fibo(n):
    return fibo(n-1) + fibo(n-2) if n>=2 else 1
fibo(100)


573147844013817084101

In [1]:
import random
random.choices([1,2,3])

[1]